CREATE DATABASE IF NOT EXISTS mobcar;

USE mobcar;

CREATE TABLE IF NOT EXISTS user (
    userID INT AUTO_INCREMENT PRIMARY KEY,
    userNome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    senha TEXT(1000) NOT NULL,
    dataRegistro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS client (
    clientID INT PRIMARY KEY,
    cnh VARCHAR(11) PRIMARY KEY
);

ALTER TABLE client 
ADD CONSTRAINT fk_client_user
FOREIGN KEY clientID 
REFERENCES user(id)
ON DELETE CASCADE
ON UPDATE CASCADE;

CREATE TABLE IF NOT EXISTS marca (
    marcaID INT AUTO_INCREMENT PRIMARY KEY,
    marcaNome VARCHAR(255) NOT NULL,

);

CREATE TABLE IF NOT EXISTS car (
    carID INT AUTO_INCREMENT PRIMARY KEY,
    placa VARCHAR(7) NOT NULL,
    marca VARCHAR(255) NOT NULL,
    modelo VARCHAR(255) NOT NULL,
    diaria float NOT NULL,
    cor VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS rent (
    rentUserID INT PRIMARY KEY,
    rentCarID INT PRIMARY KEY,
    dataRent TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    dataDevolucao TIMESTAMP
);

ALTER TABLE rent ADD CONSTRAINT fk_rent_user FOREIGN KEY rentUserID REFERENCES user(userID);
ALTER TABLE rent ADD CONSTRAINT fk_rent_car FOREIGN KEY rentCarID REFERENCES car(carID);